platform :ios, '9.0'

target 'iOS Todo App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Todo App
    pod 'SwipeCellKit'

end
